name: extract_dataset_meta
namespace: workflows
argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        __merge__: /src/api/file_raw.yaml
        required: true
        direction: input
  - name: Outputs
    arguments:
      - name: --output
        type: file
        required: true
        direction: output
        example: meta.yaml
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
dependencies:
  - name: utils/extract_uns_metadata
    repository: openproblems
runners:
  - type: nextflow
